"""Add cascade delete to patient relations

Revision ID: 0b8762da67b9
Revises: 20251109_0001
Create Date: 2025-11-14 19:12:45.201779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8762da67b9'
down_revision = '20251109_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('epc_ibfk_1'), 'epc', type_='foreignkey')
    op.create_foreign_key(None, 'epc', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'epc', type_='foreignkey')
    op.create_foreign_key(op.f('epc_ibfk_1'), 'epc', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
