"""add_multitenancy_tables

Revision ID: 82c4908f8ccc
Revises: b326df34e12a
Create Date: 2026-01-27 16:29:00.176493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c4908f8ccc'
down_revision: Union[str, Sequence[str], None] = 'b326df34e12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('api_rate_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admissions', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'admissions', 'tenants', ['tenant_id'], ['id'])
    op.add_column('branding', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'branding', 'tenants', ['tenant_id'], ['id'])
    op.add_column('epc', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'epc', 'tenants', ['tenant_id'], ['id'])
    op.add_column('patients', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'tenant_id')
    op.drop_constraint(None, 'epc', type_='foreignkey')
    op.drop_column('epc', 'tenant_id')
    op.drop_constraint(None, 'branding', type_='foreignkey')
    op.drop_column('branding', 'tenant_id')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_column('admissions', 'tenant_id')
    op.drop_table('tenant_api_keys')
    op.drop_table('tenants')
    # ### end Alembic commands ###
