"""expand_tenant_integration_options

Revision ID: a8f4008b2bf0
Revises: 82c4908f8ccc
Create Date: 2026-01-27 16:58:28.455865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f4008b2bf0'
down_revision: Union[str, Sequence[str], None] = '82c4908f8ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add integration_type with default first (for existing rows)
    op.add_column('tenants', sa.Column('integration_type', sa.String(length=20), nullable=False, server_default='inbound'))
    # Update existing Markey tenant to inbound (they provide us data)
    op.execute("UPDATE tenants SET integration_type = 'inbound' WHERE integration_type IS NULL OR integration_type = ''")
    
    op.add_column('tenants', sa.Column('external_endpoint', sa.String(length=512), nullable=True))
    op.add_column('tenants', sa.Column('external_token', sa.String(length=512), nullable=True))
    op.add_column('tenants', sa.Column('external_auth_type', sa.String(length=20), nullable=True, server_default='bearer'))
    op.add_column('tenants', sa.Column('external_headers', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('allowed_scopes', sa.String(length=512), nullable=True, server_default='read_patients,read_epc'))
    op.add_column('tenants', sa.Column('webhook_secret', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('tenants', 'webhook_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'webhook_url',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'webhook_secret')
    op.drop_column('tenants', 'allowed_scopes')
    op.drop_column('tenants', 'external_headers')
    op.drop_column('tenants', 'external_auth_type')
    op.drop_column('tenants', 'external_token')
    op.drop_column('tenants', 'external_endpoint')
    op.drop_column('tenants', 'integration_type')
    # ### end Alembic commands ###
