"""Initial_Postgres_Schema

Revision ID: b326df34e12a
Revises: 
Create Date: 2026-01-27 15:08:02.954445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b326df34e12a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_nombre', sa.String(length=160), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('header_linea1', sa.String(length=255), nullable=True),
    sa.Column('header_linea2', sa.String(length=255), nullable=True),
    sa.Column('footer_linea1', sa.String(length=255), nullable=True),
    sa.Column('footer_linea2', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epc_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('epc_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('by', sa.String(length=120), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('cuil', sa.String(length=20), nullable=True),
    sa.Column('obra_social', sa.String(length=80), nullable=True),
    sa.Column('nro_beneficiario', sa.String(length=50), nullable=True),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=10), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'internacion'"), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('domicilio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('habitacion', sa.String(length=40), nullable=True),
    sa.Column('cama', sa.String(length=40), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_egreso', sa.DateTime(), nullable=True),
    sa.Column('protocolo', sa.String(length=60), nullable=True),
    sa.Column('admision_num', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'internacion'"), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_status',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('epc',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('admission_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('version_actual_oid', sa.String(length=64), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('diagnostico_principal_cie10', sa.String(length=15), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('medico_responsable', sa.String(length=120), nullable=True),
    sa.Column('firmado_por_medico', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('motivo_internacion', sa.Text(), nullable=True),
    sa.Column('evolucion', sa.Text(), nullable=True),
    sa.Column('procedimientos', sa.Text(), nullable=True),
    sa.Column('interconsultas', sa.Text(), nullable=True),
    sa.Column('medicacion', sa.Text(), nullable=True),
    sa.Column('indicaciones_alta', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('last_edited_by', sa.String(length=36), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('has_manual_changes', sa.Boolean(), nullable=True),
    sa.Column('regenerated_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epc')
    op.drop_table('users')
    op.drop_table('patient_status')
    op.drop_table('admissions')
    op.drop_table('roles')
    op.drop_table('patients')
    op.drop_table('epc_events')
    op.drop_table('branding')
    # ### end Alembic commands ###
